#!/usr/bin/env bash
#world wide web
print_metadata ()
{
    dig_result=$(dig "$2.$1" | grep -A1 'ANSWER SECTION:' | tail -1)

    printf "The subdomain %s is a " "$2"
    echo $dig_result | awk -F' ' '{ printf $4 }'
    printf " record and points to "
    echo $dig_result | awk -F' ' '{ printf $5 }'
    echo ""
}

if [ -z "$2" ]; then
   for subs in "www" "lb-01" "web-01" "web-02"
   do
       print_metadata "$1" "$subs"
   done
else
    print_metadata "$1" "$2"
fi