#!/usr/bin/env bash
# secure transfer file

args_count=$#

if [ $args_count -le 3 ];
then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
	exit
fi

file_path=$1
ip=$2
username=$3
private_key=$4

scp -i "$private_key" "$file_path" "$username@$ip:~/"
