#!/usr/bin/env bash
# redirection

sudo apt-get update -y
sudo apt-get install -y nginx
sed -i '/listen 80 default_server/a location /redirect_me { return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4; }' /etc/nginx/sites-available/default
sudo service nginx start
