#!/usr/bin/env bash
# setup server
sudo apt-get update -y
sudo apt-get install -y nginx
sudo sed -i "/server {/a add_header X-Served-By $HOSTNAME;" /etc/nginx/sites-available/default
sudo service nginx restart
