#!/usr/bin/env bash
# display text infinitely

pid_file="/var/run/myscript.pid"

echo $$ > $pid_file

trap 'echo "Y U no love me?!"' SIGINT
trap "echo 'I hate the kill command'" SIGTERM
trap "rm $pid_file && exit" SIGTERM
trap "rm $pid_file && exit" SIGQUIT

while true; do
	echo "To infinity and beyond"
	sleep 2
done
