#!/usr/bin/env bash
# Read and cut

while read -r line;
do
    # 1, 3, 6
    username=$(echo "$line" | cut -d ':' -f1)
    id=$(echo "$line" | cut -d ':' -f3)
    home_path=$(echo "$line" | cut -d ':' -f6)
    echo "$username:$id:$home_path"
done < "/etc/passwd"
