#!/usr/bin/env bash
# this is a bash script that print best school 10 and hi  times use while

a=1
while [ $a -lt 11 ]
do
	if [ $a = 4 ];
	then
		echo "bad Luck"
	elif [ $a = 8 ];
	then
		echo "good Luck"
	else
		echo "Best School"
	fi
((a++))
done
