#!/usr/bin/env bash
# setup nginx user
useradd -s /bin/false nginx
chmod 644 /etc/nginx/nginx.conf
sed -i 's/^user .*;/user nginx;/' /etc/nginx/nginx.conf
sed -i 's/80/8080/g' /etc/nginx/sites-available/default
service nginx restart
